export { Home } from "./Home";
export { Admin } from "./Admin";
export { ProductList } from "./ProductList";
export { ProductDetail } from "./ProductDetail";
export { Contact } from "./contact/Contact";
export { ContactPh } from "./contact/ContactPh";
export { ContactEu } from "./contact/ContactEu";
export { ContactUs } from "./contact/ContactUs";
export { PageNotFound } from "./PageNotFound";
